### PR TITLE
Updated spelling

### PR DESCRIPTION
**Pull request by michaeltarleton**

### CODE REVIEW

**Comment by shmup** [comment]
here's a new word for you, @michaeltarleton:

fre·quen·cy
ˈfrēkwənsē - noun
1. the rate at which something occurs or is repeated over a particular period of time or in a given sample.

**Comment by shmup** [comment]
@michaeltarleton, yo:

Frecency is any heuristic that combines the frequency and recency into a single measure.

In its simplest form the frequency and recency rating can be added to form a frecency rating. The ratings can be found by sorting items by most recent and most frequent respectively. A decayed calculation using logarithms can also be used.

https://en.wikipedia.org/wiki/Frecency

**Comment by michaeltarleton** [comment]
Wow, didn't know this. Thanks for pointing it out. (facepalm)

**Comment by brandonsturgeon** [comment]
@michaeltarleton Not a big deal at all, but since this is all squared away, would you mind closing the pull request? :)

**Comment by michaeltarleton** [comment]
Sure thing

**Pull request closed without merging**
